spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    open-in-view: false
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect